### ISSUE TITLE
FixedColumns not working with bootstrap accordion

### ISSUE THREAD

**Issue by ddeath** [DataTables/FixedColumns#47]
The fixed column is not fixed:

http://jsfiddle.net/vdyyuyev/

**Comment by ddeath** [comment]
Hmm, well it is working, if I add setTimeout()... So this is probably not problem of fixedColumns...

**Comment by ddeath** [comment]
Lol this is weird same on Firefox, not working unless I open close inspector....

**Comment by DataTables** [comment]
Because the table is hidden when it is initialised it has zero height and width. Therefore there is no way for DataTables to layout the fixed elements. What you need to do is call the [fixedColumns().relayout()` method](http://datatables.net/reference/api/fixedColumns().relayout()) when the table is made visible.

You'll need an event from Bootstrap (`shown` probably) to know when the table has been made visible so you can call that method.

**Comment by DataTables** [comment]
Going to close this issue now.
