### ISSUE TITLE
The license can not be determined on Webjars packaging

### ISSUE THREAD

**Issue by masa-kunikata** [DataTables/FixedColumns#70]
When I tried to package FixedColumns ver.3.2.4 to webjar on Webjars.org(https://www.webjars.org/),
I got the error message below.

>  All attempts to determine an acceptable license have been exhausted. The bower.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/DataTables/FixedColumns.git
> The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
> The provided licenses were: 
> This problem will likely need to be resolved by working with the library maintainers directly.
> 

I don't know why they can't determine the licence from the "license.txt" file.
Will adding `"lincense": "MIT"` node to the bower.json be their "spec-compliant license definition"?

**Comment by DataTables** [comment]
I've added it in 0198fbdbcefedd853803be9d652a7b3d3e5f5e07.

I would point out that this isn't the repo you want to include though - its the source repo rather than one suitable for distribution. [Dist-DataTables-FixedHeader](https://github.com/DataTables/Dist-DataTables-FixedHeader) is the one you want to use (although oddly it looks to be out of sync - i'll fix that).

**Comment by masa-kunikata** [comment]
Thank you very much!
I'll try the "Dist-~~~" repo.
